### ISSUE TITLE
[Feature Request] Screencasts for all difference between parameters?

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/FindCursor#4]
### Briefly

May you make 4 screencasts for each parameters value?

### Detail

It would be nice, if you make 4 screencasts for `{"reverse": false, "pan": false}`, `{"reverse": false, "pan": true}`, `{"reverse": true, "pan": false}` and `{"reverse": true, "pan": true}`.

### Did not help

I read [documentation](http://facelessuser.github.io/FindCursor/usage/#command), but on practice results for each arguments no difference for me. I get the same result if I run the command `find_cursor` with different arguments.

Thanks.

**Comment by facelessuser** [comment]
> May you make 4 screencasts for each parameters value?

If I get a chance.

> I read documentation, but on practice results for each arguments no difference for me. I get the same result if I run the command find_cursor with different arguments.

I can try to explain here a little more just to make this clear.

- reverse should be straight forward; instead of searching top to bottom of the page, it will search bottom to top.
- pan should iterate through each cursor.  `pan == true` will focus each cursor in the center (if it can). `pan == false` will scroll all the current visible cursors off screen and scroll down to the next cursor.  It is kind of like the difference of using the down key vs page down key.  If you only have a couple of cursor on the screen and they are spread far apart, the feature will seem to act the same.

**Comment by facelessuser** [comment]
Note to self: a screen cast would be nice, but should probably should also explain things better in the docs too.

**Comment by Kristinita** [comment]
What I do wrong? I get a same result for each argument:

![Find Cursor](http://i.imgur.com/mXie7XN.gif)

Thanks.

**Comment by facelessuser** [comment]
Because each cursor is so far away from the others, the feature will behave the same.  Let me throw together a screencast real quick.

**Comment by facelessuser** [comment]
![findcursor](https://cloud.githubusercontent.com/assets/1055125/19378990/104e0b24-91ad-11e6-94bc-93edfe554208.gif)

It works fine with shortcuts.  I think the reason why it seems the same for you is because you need to run the command again while the cursors are highlighted.  If you wait till the cursors go back to normal to run the command again, it won't iterate.  That is why this works better as a keymap instead of a command palette.  I forgot that it works this way.  Maybe command palette is not the best way to use this if you want to iterate.

**Comment by facelessuser** [comment]
I think my description of pan was backwards earlier.  Iterative is with `pan == false`.  Whoops.  I guess I should think about changing the name to something more clear, it even confused me.

**Comment by facelessuser** [comment]
Yeah, the documentation was right, it is just late, and my brain has stopped working.  I won't be able to respond until tomorrow.

**Comment by facelessuser** [comment]
I've added the screen cast to the readme and the documentation via commit https://github.com/facelessuser/FindCursor/commit/a627f7be0cf609dfc989d0c1199dc979645abfb7.  I have not yet regenerated the documentation as I have a couple more changes before release.

**Comment by Kristinita** [comment]
@facelessuser , all right, we wait new release.

**Comment by facelessuser** [comment]
Released

**Comment by Kristinita** [comment]
Thank you very much!
